### ISSUE TITLE
Repository tags wrong (?)

### ISSUE THREAD

**Issue by antorqs** [Stonks-Luma-Liberty/GuiltySpark#46]
Hey! I stumbled upon this repo. I'm definitely checking it out, but I noticed this is tagged as a python project but it's all a nodejs/typescript project. Maybe you want to fix that to help discoverability. Anyways, have a good day.

**Comment by ChristianPerez34** [comment]
Thanks for pointing that out! Originally was going to build this in Python, however, ended up doing it with TypeScript and NodeJS
